// Mocks generated by Mockito 5.4.4 from annotations
// in mobile/test/features/profile/presentation/screens/customer/addresses_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:mobile/features/notifications/data/models/customer_notification.dart'
    as _i3;
import 'package:mobile/features/notifications/data/models/vendor_notification.dart'
    as _i4;
import 'package:mobile/features/profile/data/models/address.dart' as _i8;
import 'package:mobile/features/profile/presentation/providers/address_provider.dart'
    as _i7;
import 'package:mobile/providers/notification_provider.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [NotificationProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationProvider extends _i1.Mock
    implements _i2.NotificationProvider {
  MockNotificationProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.CustomerNotification> get notifications => (super.noSuchMethod(
        Invocation.getter(#notifications),
        returnValue: <_i3.CustomerNotification>[],
      ) as List<_i3.CustomerNotification>);

  @override
  List<_i4.VendorNotification> get vendorNotifications => (super.noSuchMethod(
        Invocation.getter(#vendorNotifications),
        returnValue: <_i4.VendorNotification>[],
      ) as List<_i4.VendorNotification>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  int get unreadCount => (super.noSuchMethod(
        Invocation.getter(#unreadCount),
        returnValue: 0,
      ) as int);

  @override
  int get vendorUnreadCount => (super.noSuchMethod(
        Invocation.getter(#vendorUnreadCount),
        returnValue: 0,
      ) as int);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> loadNotifications() => (super.noSuchMethod(
        Invocation.method(
          #loadNotifications,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadVendorNotifications({bool? force = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadVendorNotifications,
          [],
          {#force: force},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> markAsRead(String? notificationId) => (super.noSuchMethod(
        Invocation.method(
          #markAsRead,
          [notificationId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> markAllAsRead() => (super.noSuchMethod(
        Invocation.method(
          #markAllAsRead,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AddressProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddressProvider extends _i1.Mock implements _i7.AddressProvider {
  MockAddressProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i8.Address> get addresses => (super.noSuchMethod(
        Invocation.getter(#addresses),
        returnValue: <_i8.Address>[],
      ) as List<_i8.Address>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  List<Map<String, dynamic>> get countries => (super.noSuchMethod(
        Invocation.getter(#countries),
        returnValue: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  List<Map<String, dynamic>> get cities => (super.noSuchMethod(
        Invocation.getter(#cities),
        returnValue: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  List<Map<String, dynamic>> get districts => (super.noSuchMethod(
        Invocation.getter(#districts),
        returnValue: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  List<Map<String, dynamic>> get localities => (super.noSuchMethod(
        Invocation.getter(#localities),
        returnValue: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  bool get isLoadingLocations => (super.noSuchMethod(
        Invocation.getter(#isLoadingLocations),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> loadAddresses() => (super.noSuchMethod(
        Invocation.method(
          #loadAddresses,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAddress(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteAddress,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setDefaultAddress(String? id) => (super.noSuchMethod(
        Invocation.method(
          #setDefaultAddress,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveAddress(
    Map<String, dynamic>? data, {
    String? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAddress,
          [data],
          {#id: id},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadCountries() => (super.noSuchMethod(
        Invocation.method(
          #loadCountries,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadCities(String? countryId) => (super.noSuchMethod(
        Invocation.method(
          #loadCities,
          [countryId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadDistricts(String? cityId) => (super.noSuchMethod(
        Invocation.method(
          #loadDistricts,
          [cityId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadLocalities(String? districtId) => (super.noSuchMethod(
        Invocation.method(
          #loadLocalities,
          [districtId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void clearLocationData() => super.noSuchMethod(
        Invocation.method(
          #clearLocationData,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
