// Mocks generated by Mockito 5.4.4 from annotations
// in mobile/test/features/products/presentation/screens/customer/product_detail_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i21;

import 'package:dio/dio.dart' as _i2;
import 'package:flutter/material.dart' as _i20;
import 'package:mobile/features/auth/presentation/providers/auth_provider.dart'
    as _i17;
import 'package:mobile/features/campaigns/data/models/campaign.dart' as _i13;
import 'package:mobile/features/cart/data/models/cart_item.dart' as _i19;
import 'package:mobile/features/cart/presentation/providers/cart_provider.dart'
    as _i18;
import 'package:mobile/features/coupons/data/models/coupon.dart' as _i14;
import 'package:mobile/features/home/data/models/promotional_banner.dart'
    as _i10;
import 'package:mobile/features/notifications/data/models/customer_notification.dart'
    as _i12;
import 'package:mobile/features/orders/data/models/order.dart' as _i4;
import 'package:mobile/features/products/data/models/product.dart' as _i3;
import 'package:mobile/features/reviews/data/models/review.dart' as _i6;
import 'package:mobile/features/search/data/models/search_dtos.dart' as _i5;
import 'package:mobile/features/vendors/data/models/delivery_zone_models.dart'
    as _i15;
import 'package:mobile/features/vendors/data/models/vendor.dart' as _i9;
import 'package:mobile/services/api_service.dart' as _i7;
import 'package:mobile/services/logger_service.dart' as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProduct_1 extends _i1.SmartFake implements _i3.Product {
  _FakeProduct_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrder_2 extends _i1.SmartFake implements _i4.Order {
  _FakeOrder_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePagedResultDto_3<T> extends _i1.SmartFake
    implements _i5.PagedResultDto<T> {
  _FakePagedResultDto_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReview_4 extends _i1.SmartFake implements _i6.Review {
  _FakeReview_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductReviewsSummary_5 extends _i1.SmartFake
    implements _i6.ProductReviewsSummary {
  _FakeProductReviewsSummary_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i7.ApiService {
  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
        returnValueForMissingStub: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  void notifyLogout() => super.noSuchMethod(
        Invocation.method(
          #notifyLogout,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetLogout() => super.noSuchMethod(
        Invocation.method(
          #resetLogout,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<List<_i9.Vendor>> getVendors({
    int? vendorType,
    int? page = 1,
    int? pageSize = 6,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVendors,
          [],
          {
            #vendorType: vendorType,
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue: _i8.Future<List<_i9.Vendor>>.value(<_i9.Vendor>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i9.Vendor>>.value(<_i9.Vendor>[]),
      ) as _i8.Future<List<_i9.Vendor>>);

  @override
  _i8.Future<List<_i3.Product>> getProducts(
    String? vendorId, {
    int? page = 1,
    int? pageSize = 6,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProducts,
          [vendorId],
          {
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue: _i8.Future<List<_i3.Product>>.value(<_i3.Product>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i3.Product>>.value(<_i3.Product>[]),
      ) as _i8.Future<List<_i3.Product>>);

  @override
  _i8.Future<List<_i3.Product>> getPopularProducts({
    int? page = 1,
    int? pageSize = 6,
    int? vendorType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularProducts,
          [],
          {
            #page: page,
            #pageSize: pageSize,
            #vendorType: vendorType,
          },
        ),
        returnValue: _i8.Future<List<_i3.Product>>.value(<_i3.Product>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i3.Product>>.value(<_i3.Product>[]),
      ) as _i8.Future<List<_i3.Product>>);

  @override
  _i8.Future<List<_i10.PromotionalBanner>> getBanners({
    String? language,
    int? vendorType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBanners,
          [],
          {
            #language: language,
            #vendorType: vendorType,
          },
        ),
        returnValue: _i8.Future<List<_i10.PromotionalBanner>>.value(
            <_i10.PromotionalBanner>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i10.PromotionalBanner>>.value(
                <_i10.PromotionalBanner>[]),
      ) as _i8.Future<List<_i10.PromotionalBanner>>);

  @override
  _i8.Future<_i3.Product> getProduct(String? productId) => (super.noSuchMethod(
        Invocation.method(
          #getProduct,
          [productId],
        ),
        returnValue: _i8.Future<_i3.Product>.value(_FakeProduct_1(
          this,
          Invocation.method(
            #getProduct,
            [productId],
          ),
        )),
        returnValueForMissingStub: _i8.Future<_i3.Product>.value(_FakeProduct_1(
          this,
          Invocation.method(
            #getProduct,
            [productId],
          ),
        )),
      ) as _i8.Future<_i3.Product>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getCountries() => (super.noSuchMethod(
        Invocation.method(
          #getCountries,
          [],
        ),
        returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getLocationCities(String? countryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocationCities,
          [countryId],
        ),
        returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getLocationDistricts(String? cityId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocationDistricts,
          [cityId],
        ),
        returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getLocationLocalities(
          String? districtId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocationLocalities,
          [districtId],
        ),
        returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<List<_i3.Product>> getSimilarProducts(
    String? productId, {
    int? page = 1,
    int? pageSize = 6,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSimilarProducts,
          [productId],
          {
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue: _i8.Future<List<_i3.Product>>.value(<_i3.Product>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i3.Product>>.value(<_i3.Product>[]),
      ) as _i8.Future<List<_i3.Product>>);

  @override
  _i8.Future<_i4.Order> createOrder(
    String? vendorId,
    Map<String, int>? items, {
    String? deliveryAddressId,
    String? paymentMethod,
    String? note,
    String? couponCode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrder,
          [
            vendorId,
            items,
          ],
          {
            #deliveryAddressId: deliveryAddressId,
            #paymentMethod: paymentMethod,
            #note: note,
            #couponCode: couponCode,
          },
        ),
        returnValue: _i8.Future<_i4.Order>.value(_FakeOrder_2(
          this,
          Invocation.method(
            #createOrder,
            [
              vendorId,
              items,
            ],
            {
              #deliveryAddressId: deliveryAddressId,
              #paymentMethod: paymentMethod,
              #note: note,
              #couponCode: couponCode,
            },
          ),
        )),
        returnValueForMissingStub: _i8.Future<_i4.Order>.value(_FakeOrder_2(
          this,
          Invocation.method(
            #createOrder,
            [
              vendorId,
              items,
            ],
            {
              #deliveryAddressId: deliveryAddressId,
              #paymentMethod: paymentMethod,
              #note: note,
              #couponCode: couponCode,
            },
          ),
        )),
      ) as _i8.Future<_i4.Order>);

  @override
  _i8.Future<Map<String, dynamic>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> register(
    String? email,
    String? password,
    String? fullName, {
    String? language,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            email,
            password,
            fullName,
          ],
          {#language: language},
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> vendorRegister({
    required String? email,
    required String? password,
    required String? fullName,
    required String? businessName,
    required String? phone,
    String? address,
    String? city,
    String? description,
    String? language,
    int? vendorType = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #vendorRegister,
          [],
          {
            #email: email,
            #password: password,
            #fullName: fullName,
            #businessName: businessName,
            #phone: phone,
            #address: address,
            #city: city,
            #description: description,
            #language: language,
            #vendorType: vendorType,
          },
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> courierRegister({
    required String? email,
    required String? password,
    required String? fullName,
    required String? phone,
    required int? vehicleType,
    String? language,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #courierRegister,
          [],
          {
            #email: email,
            #password: password,
            #fullName: fullName,
            #phone: phone,
            #vehicleType: vehicleType,
            #language: language,
          },
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  void setAuthToken(String? token) => super.noSuchMethod(
        Invocation.method(
          #setAuthToken,
          [token],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> forgotPassword(
    String? email, {
    String? language,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [email],
          {#language: language},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<String> verifyResetCode(
    String? email,
    String? code,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyResetCode,
          [
            email,
            code,
          ],
        ),
        returnValue: _i8.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #verifyResetCode,
            [
              email,
              code,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #verifyResetCode,
            [
              email,
              code,
            ],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<void> resetPassword(
    String? email,
    String? token,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [
            email,
            token,
            newPassword,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> confirmEmail(
    String? token,
    String? email,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmEmail,
          [
            token,
            email,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<Map<String, dynamic>> verifyEmailCode(
    String? email,
    String? code,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyEmailCode,
          [
            email,
            code,
          ],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> resendVerificationCode(
    String? email, {
    String? language,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resendVerificationCode,
          [email],
          {#language: language},
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> externalLogin({
    required String? provider,
    required String? idToken,
    required String? email,
    required String? fullName,
    String? language,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #externalLogin,
          [],
          {
            #provider: provider,
            #idToken: idToken,
            #email: email,
            #fullName: fullName,
            #language: language,
          },
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<void> registerDeviceToken(
    String? token,
    String? deviceType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerDeviceToken,
          [
            token,
            deviceType,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i12.CustomerNotification>> getCustomerNotifications() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCustomerNotifications,
          [],
        ),
        returnValue: _i8.Future<List<_i12.CustomerNotification>>.value(
            <_i12.CustomerNotification>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i12.CustomerNotification>>.value(
                <_i12.CustomerNotification>[]),
      ) as _i8.Future<List<_i12.CustomerNotification>>);

  @override
  _i8.Future<Map<String, dynamic>> getCart() => (super.noSuchMethod(
        Invocation.method(
          #getCart,
          [],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<void> addToCart(
    String? productId,
    int? quantity,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToCart,
          [
            productId,
            quantity,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateCartItem(
    String? itemId,
    int? quantity,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCartItem,
          [
            itemId,
            quantity,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> clearCart() => (super.noSuchMethod(
        Invocation.method(
          #clearCart,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> removeFromCart(String? itemId) => (super.noSuchMethod(
        Invocation.method(
          #removeFromCart,
          [itemId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<Map<String, dynamic>> getProfile() => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<void> updateProfile(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [data],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> changePassword(
    String? currentPassword,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [
            currentPassword,
            newPassword,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<dynamic>> getAddresses() => (super.noSuchMethod(
        Invocation.method(
          #getAddresses,
          [],
        ),
        returnValue: _i8.Future<List<dynamic>>.value(<dynamic>[]),
        returnValueForMissingStub: _i8.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i8.Future<List<dynamic>>);

  @override
  _i8.Future<void> createAddress(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAddress,
          [data],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateAddress(
    String? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAddress,
          [
            id,
            data,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteAddress(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteAddress,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setDefaultAddress(String? id) => (super.noSuchMethod(
        Invocation.method(
          #setDefaultAddress,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i5.PagedResultDto<_i5.ProductDto>> getFavorites({
    int? page = 1,
    int? pageSize = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [],
          {
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue: _i8.Future<_i5.PagedResultDto<_i5.ProductDto>>.value(
            _FakePagedResultDto_3<_i5.ProductDto>(
          this,
          Invocation.method(
            #getFavorites,
            [],
            {
              #page: page,
              #pageSize: pageSize,
            },
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.PagedResultDto<_i5.ProductDto>>.value(
                _FakePagedResultDto_3<_i5.ProductDto>(
          this,
          Invocation.method(
            #getFavorites,
            [],
            {
              #page: page,
              #pageSize: pageSize,
            },
          ),
        )),
      ) as _i8.Future<_i5.PagedResultDto<_i5.ProductDto>>);

  @override
  _i8.Future<Map<String, dynamic>> getNotificationSettings() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotificationSettings,
          [],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<void> updateNotificationSettings(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNotificationSettings,
          [data],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> addToFavorites(String? productId) => (super.noSuchMethod(
        Invocation.method(
          #addToFavorites,
          [productId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> removeFromFavorites(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromFavorites,
          [productId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<bool> isFavorite(String? productId) => (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [productId],
        ),
        returnValue: _i8.Future<bool>.value(false),
        returnValueForMissingStub: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<List<dynamic>> getOrders({int? vendorType}) => (super.noSuchMethod(
        Invocation.method(
          #getOrders,
          [],
          {#vendorType: vendorType},
        ),
        returnValue: _i8.Future<List<dynamic>>.value(<dynamic>[]),
        returnValueForMissingStub: _i8.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i8.Future<List<dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getOrderDetails(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrderDetails,
          [orderId],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getOrderDetailFull(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrderDetailFull,
          [orderId],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<void> cancelOrder(
    String? orderId,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelOrder,
          [
            orderId,
            reason,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i13.Campaign>> getCampaigns({
    int? vendorType,
    String? cityId,
    String? districtId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCampaigns,
          [],
          {
            #vendorType: vendorType,
            #cityId: cityId,
            #districtId: districtId,
          },
        ),
        returnValue: _i8.Future<List<_i13.Campaign>>.value(<_i13.Campaign>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i13.Campaign>>.value(<_i13.Campaign>[]),
      ) as _i8.Future<List<_i13.Campaign>>);

  @override
  _i8.Future<List<_i14.Coupon>> getCoupons() => (super.noSuchMethod(
        Invocation.method(
          #getCoupons,
          [],
        ),
        returnValue: _i8.Future<List<_i14.Coupon>>.value(<_i14.Coupon>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i14.Coupon>>.value(<_i14.Coupon>[]),
      ) as _i8.Future<List<_i14.Coupon>>);

  @override
  _i8.Future<_i14.Coupon?> validateCoupon(
    String? code, {
    String? cityId,
    String? districtId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateCoupon,
          [code],
          {
            #cityId: cityId,
            #districtId: districtId,
          },
        ),
        returnValue: _i8.Future<_i14.Coupon?>.value(),
        returnValueForMissingStub: _i8.Future<_i14.Coupon?>.value(),
      ) as _i8.Future<_i14.Coupon?>);

  @override
  _i8.Future<void> cancelOrderItem(
    String? customerOrderItemId,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelOrderItem,
          [
            customerOrderItemId,
            reason,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i5.PagedResultDto<_i5.ProductDto>> searchProducts(
          _i5.ProductSearchRequestDto? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchProducts,
          [request],
        ),
        returnValue: _i8.Future<_i5.PagedResultDto<_i5.ProductDto>>.value(
            _FakePagedResultDto_3<_i5.ProductDto>(
          this,
          Invocation.method(
            #searchProducts,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.PagedResultDto<_i5.ProductDto>>.value(
                _FakePagedResultDto_3<_i5.ProductDto>(
          this,
          Invocation.method(
            #searchProducts,
            [request],
          ),
        )),
      ) as _i8.Future<_i5.PagedResultDto<_i5.ProductDto>>);

  @override
  _i8.Future<_i5.PagedResultDto<_i5.VendorDto>> searchVendors(
          _i5.VendorSearchRequestDto? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchVendors,
          [request],
        ),
        returnValue: _i8.Future<_i5.PagedResultDto<_i5.VendorDto>>.value(
            _FakePagedResultDto_3<_i5.VendorDto>(
          this,
          Invocation.method(
            #searchVendors,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.PagedResultDto<_i5.VendorDto>>.value(
                _FakePagedResultDto_3<_i5.VendorDto>(
          this,
          Invocation.method(
            #searchVendors,
            [request],
          ),
        )),
      ) as _i8.Future<_i5.PagedResultDto<_i5.VendorDto>>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getCategories({
    String? language,
    int? vendorType,
    int? page = 1,
    int? pageSize = 6,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
          {
            #language: language,
            #vendorType: vendorType,
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<List<String>> getCities({
    int? page = 1,
    int? pageSize = 6,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCities,
          [],
          {
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue: _i8.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i8.Future<List<String>>.value(<String>[]),
      ) as _i8.Future<List<String>>);

  @override
  _i8.Future<List<_i5.AutocompleteResultDto>> autocomplete(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #autocomplete,
          [query],
        ),
        returnValue: _i8.Future<List<_i5.AutocompleteResultDto>>.value(
            <_i5.AutocompleteResultDto>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i5.AutocompleteResultDto>>.value(
                <_i5.AutocompleteResultDto>[]),
      ) as _i8.Future<List<_i5.AutocompleteResultDto>>);

  @override
  _i8.Future<String> getGoogleMapsApiKey() => (super.noSuchMethod(
        Invocation.method(
          #getGoogleMapsApiKey,
          [],
        ),
        returnValue: _i8.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #getGoogleMapsApiKey,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #getGoogleMapsApiKey,
            [],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getVendorsForMap({
    double? userLatitude,
    double? userLongitude,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVendorsForMap,
          [],
          {
            #userLatitude: userLatitude,
            #userLongitude: userLongitude,
          },
        ),
        returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<Map<String, dynamic>> getDeliveryTracking(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDeliveryTracking,
          [orderId],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<void> updateCourierLocation(
    String? courierId,
    double? latitude,
    double? longitude,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCourierLocation,
          [
            courierId,
            latitude,
            longitude,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<Map<String, dynamic>> getCourierLocation(String? courierId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCourierLocation,
          [courierId],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<_i6.Review> createReview(
    String? targetId,
    String? targetType,
    int? rating,
    String? comment,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createReview,
          [
            targetId,
            targetType,
            rating,
            comment,
          ],
        ),
        returnValue: _i8.Future<_i6.Review>.value(_FakeReview_4(
          this,
          Invocation.method(
            #createReview,
            [
              targetId,
              targetType,
              rating,
              comment,
            ],
          ),
        )),
        returnValueForMissingStub: _i8.Future<_i6.Review>.value(_FakeReview_4(
          this,
          Invocation.method(
            #createReview,
            [
              targetId,
              targetType,
              rating,
              comment,
            ],
          ),
        )),
      ) as _i8.Future<_i6.Review>);

  @override
  _i8.Future<_i6.ProductReviewsSummary> getProductReviews(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductReviews,
          [productId],
        ),
        returnValue: _i8.Future<_i6.ProductReviewsSummary>.value(
            _FakeProductReviewsSummary_5(
          this,
          Invocation.method(
            #getProductReviews,
            [productId],
          ),
        )),
        returnValueForMissingStub: _i8.Future<_i6.ProductReviewsSummary>.value(
            _FakeProductReviewsSummary_5(
          this,
          Invocation.method(
            #getProductReviews,
            [productId],
          ),
        )),
      ) as _i8.Future<_i6.ProductReviewsSummary>);

  @override
  _i8.Future<List<_i6.Review>> getVendorReviews(String? vendorId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVendorReviews,
          [vendorId],
        ),
        returnValue: _i8.Future<List<_i6.Review>>.value(<_i6.Review>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i6.Review>>.value(<_i6.Review>[]),
      ) as _i8.Future<List<_i6.Review>>);

  @override
  _i8.Future<List<_i6.Review>> getPendingReviews() => (super.noSuchMethod(
        Invocation.method(
          #getPendingReviews,
          [],
        ),
        returnValue: _i8.Future<List<_i6.Review>>.value(<_i6.Review>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i6.Review>>.value(<_i6.Review>[]),
      ) as _i8.Future<List<_i6.Review>>);

  @override
  _i8.Future<void> approveReview(String? reviewId) => (super.noSuchMethod(
        Invocation.method(
          #approveReview,
          [reviewId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> rejectReview(String? reviewId) => (super.noSuchMethod(
        Invocation.method(
          #rejectReview,
          [reviewId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getActiveCouriers() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveCouriers,
          [],
        ),
        returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<Map<String, dynamic>> getUserPreferences() => (super.noSuchMethod(
        Invocation.method(
          #getUserPreferences,
          [],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<void> updateUserPreferences({
    String? language,
    String? currency,
    String? timeZone,
    String? dateFormat,
    String? timeFormat,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserPreferences,
          [],
          {
            #language: language,
            #currency: currency,
            #timeZone: timeZone,
            #dateFormat: dateFormat,
            #timeFormat: timeFormat,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getSupportedLanguages() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSupportedLanguages,
          [],
        ),
        returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getSupportedCurrencies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSupportedCurrencies,
          [],
        ),
        returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<List<dynamic>> getVendorOrders({
    String? status,
    DateTime? startDate,
    DateTime? endDate,
    int? page,
    int? pageSize,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVendorOrders,
          [],
          {
            #status: status,
            #startDate: startDate,
            #endDate: endDate,
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue: _i8.Future<List<dynamic>>.value(<dynamic>[]),
        returnValueForMissingStub: _i8.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i8.Future<List<dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getVendorOrdersWithCount({
    String? status,
    DateTime? startDate,
    DateTime? endDate,
    int? page,
    int? pageSize,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVendorOrdersWithCount,
          [],
          {
            #status: status,
            #startDate: startDate,
            #endDate: endDate,
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getVendorOrder(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVendorOrder,
          [orderId],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<void> acceptOrder(String? orderId) => (super.noSuchMethod(
        Invocation.method(
          #acceptOrder,
          [orderId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> rejectOrder(
    String? orderId,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #rejectOrder,
          [
            orderId,
            reason,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateOrderStatus(
    String? orderId,
    String? status, {
    String? note,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrderStatus,
          [
            orderId,
            status,
          ],
          {#note: note},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getAvailableCouriers(
          String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableCouriers,
          [orderId],
        ),
        returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<void> assignCourierToOrder(
    String? orderId,
    String? courierId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #assignCourierToOrder,
          [
            orderId,
            courierId,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<Map<String, dynamic>> autoAssignCourier(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #autoAssignCourier,
          [orderId],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getSalesReport({
    DateTime? startDate,
    DateTime? endDate,
    String? period = r'week',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSalesReport,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
            #period: period,
          },
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getVendorSummary() => (super.noSuchMethod(
        Invocation.method(
          #getVendorSummary,
          [],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<List<_i3.Product>> getVendorProducts({
    String? category,
    bool? isAvailable,
    int? page,
    int? pageSize,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVendorProducts,
          [],
          {
            #category: category,
            #isAvailable: isAvailable,
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue: _i8.Future<List<_i3.Product>>.value(<_i3.Product>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i3.Product>>.value(<_i3.Product>[]),
      ) as _i8.Future<List<_i3.Product>>);

  @override
  _i8.Future<_i3.Product> getVendorProduct(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVendorProduct,
          [productId],
        ),
        returnValue: _i8.Future<_i3.Product>.value(_FakeProduct_1(
          this,
          Invocation.method(
            #getVendorProduct,
            [productId],
          ),
        )),
        returnValueForMissingStub: _i8.Future<_i3.Product>.value(_FakeProduct_1(
          this,
          Invocation.method(
            #getVendorProduct,
            [productId],
          ),
        )),
      ) as _i8.Future<_i3.Product>);

  @override
  _i8.Future<_i3.Product> createProduct(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProduct,
          [data],
        ),
        returnValue: _i8.Future<_i3.Product>.value(_FakeProduct_1(
          this,
          Invocation.method(
            #createProduct,
            [data],
          ),
        )),
        returnValueForMissingStub: _i8.Future<_i3.Product>.value(_FakeProduct_1(
          this,
          Invocation.method(
            #createProduct,
            [data],
          ),
        )),
      ) as _i8.Future<_i3.Product>);

  @override
  _i8.Future<void> updateProduct(
    String? productId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProduct,
          [
            productId,
            data,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteProduct(String? productId) => (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [productId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateProductAvailability(
    String? productId,
    bool? isAvailable,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProductAvailability,
          [
            productId,
            isAvailable,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateProductPrice(
    String? productId,
    double? price,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProductPrice,
          [
            productId,
            price,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<String>> getVendorProductCategories() => (super.noSuchMethod(
        Invocation.method(
          #getVendorProductCategories,
          [],
        ),
        returnValue: _i8.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i8.Future<List<String>>.value(<String>[]),
      ) as _i8.Future<List<String>>);

  @override
  _i8.Future<String> uploadProductImage(dynamic file) => (super.noSuchMethod(
        Invocation.method(
          #uploadProductImage,
          [file],
        ),
        returnValue: _i8.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #uploadProductImage,
            [file],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #uploadProductImage,
            [file],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<Map<String, dynamic>> getVendorProfile() => (super.noSuchMethod(
        Invocation.method(
          #getVendorProfile,
          [],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<void> updateVendorProfile(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateVendorProfile,
          [data],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateVendorImage(String? imageUrl) => (super.noSuchMethod(
        Invocation.method(
          #updateVendorImage,
          [imageUrl],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateBusyStatus(int? status) => (super.noSuchMethod(
        Invocation.method(
          #updateBusyStatus,
          [status],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateVendorSettings(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateVendorSettings,
          [data],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> toggleVendorActive(bool? isActive) => (super.noSuchMethod(
        Invocation.method(
          #toggleVendorActive,
          [isActive],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<Map<String, dynamic>> getVendorSettings() => (super.noSuchMethod(
        Invocation.method(
          #getVendorSettings,
          [],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getLegalContent(
    String? type,
    String? langCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLegalContent,
          [
            type,
            langCode,
          ],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<List<dynamic>> getVendorNotifications() => (super.noSuchMethod(
        Invocation.method(
          #getVendorNotifications,
          [],
        ),
        returnValue: _i8.Future<List<dynamic>>.value(<dynamic>[]),
        returnValueForMissingStub: _i8.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i8.Future<List<dynamic>>);

  @override
  _i8.Future<void> markNotificationAsRead(
    String? type,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markNotificationAsRead,
          [
            type,
            id,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> markAllNotificationsAsRead(String? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAllNotificationsAsRead,
          [type],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<dynamic> getDeliveryZones({String? cityId}) => (super.noSuchMethod(
        Invocation.method(
          #getDeliveryZones,
          [],
          {#cityId: cityId},
        ),
        returnValue: _i8.Future<dynamic>.value(),
        returnValueForMissingStub: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);

  @override
  _i8.Future<void> syncDeliveryZones(_i15.DeliveryZoneSyncDto? dto) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncDeliveryZones,
          [dto],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [LoggerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoggerService extends _i1.Mock implements _i16.LoggerService {
  @override
  _i8.Future<void> init({_i17.AuthProvider? authProvider}) =>
      (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
          {#authProvider: authProvider},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void debug(
    String? message, [
    dynamic error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #debug,
          [
            message,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void info(String? message) => super.noSuchMethod(
        Invocation.method(
          #info,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void warning(
    String? message, [
    dynamic error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #warning,
          [
            message,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void error(
    String? message, [
    dynamic error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #error,
          [
            message,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void fatal(
    String? message, [
    dynamic error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #fatal,
          [
            message,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [CartProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartProvider extends _i1.Mock implements _i18.CartProvider {
  @override
  Map<String, _i19.CartItem> get items => (super.noSuchMethod(
        Invocation.getter(#items),
        returnValue: <String, _i19.CartItem>{},
        returnValueForMissingStub: <String, _i19.CartItem>{},
      ) as Map<String, _i19.CartItem>);

  @override
  int get itemCount => (super.noSuchMethod(
        Invocation.getter(#itemCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  double get subtotalAmount => (super.noSuchMethod(
        Invocation.getter(#subtotalAmount),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get discountAmount => (super.noSuchMethod(
        Invocation.getter(#discountAmount),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get totalAmount => (super.noSuchMethod(
        Invocation.getter(#totalAmount),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i8.Future<void> applyCoupon(String? code) => (super.noSuchMethod(
        Invocation.method(
          #applyCoupon,
          [code],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void removeCoupon() => super.noSuchMethod(
        Invocation.method(
          #removeCoupon,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> loadCart() => (super.noSuchMethod(
        Invocation.method(
          #loadCart,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> addItem(
    _i3.Product? product,
    _i20.BuildContext? context,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addItem,
          [
            product,
            context,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> removeItem(String? productId) => (super.noSuchMethod(
        Invocation.method(
          #removeItem,
          [productId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> increaseQuantity(String? productId) => (super.noSuchMethod(
        Invocation.method(
          #increaseQuantity,
          [productId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> decreaseQuantity(String? productId) => (super.noSuchMethod(
        Invocation.method(
          #decreaseQuantity,
          [productId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void addListener(_i21.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i21.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
