// Mocks generated by Mockito 5.4.4 from annotations
// in mobile/test/features/products/presentation/widgets/product_card_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i8;

import 'package:flutter/material.dart' as _i7;
import 'package:mobile/features/campaigns/data/models/campaign.dart' as _i6;
import 'package:mobile/features/cart/data/models/cart_item.dart' as _i3;
import 'package:mobile/features/cart/presentation/providers/cart_provider.dart'
    as _i2;
import 'package:mobile/features/products/data/models/product.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CartProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartProvider extends _i1.Mock implements _i2.CartProvider {
  @override
  Map<String, _i3.CartItem> get items => (super.noSuchMethod(
        Invocation.getter(#items),
        returnValue: <String, _i3.CartItem>{},
        returnValueForMissingStub: <String, _i3.CartItem>{},
      ) as Map<String, _i3.CartItem>);

  @override
  int get itemCount => (super.noSuchMethod(
        Invocation.getter(#itemCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<_i4.Product> get recommendations => (super.noSuchMethod(
        Invocation.getter(#recommendations),
        returnValue: <_i4.Product>[],
        returnValueForMissingStub: <_i4.Product>[],
      ) as List<_i4.Product>);

  @override
  double get deliveryFee => (super.noSuchMethod(
        Invocation.getter(#deliveryFee),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get freeDeliveryThreshold => (super.noSuchMethod(
        Invocation.getter(#freeDeliveryThreshold),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  bool get isFreeDeliveryEnabled => (super.noSuchMethod(
        Invocation.getter(#isFreeDeliveryEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isFreeDeliveryReached => (super.noSuchMethod(
        Invocation.getter(#isFreeDeliveryReached),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  double get freeDeliveryProgress => (super.noSuchMethod(
        Invocation.getter(#freeDeliveryProgress),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get remainingForFreeDelivery => (super.noSuchMethod(
        Invocation.getter(#remainingForFreeDelivery),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get subtotalAmount => (super.noSuchMethod(
        Invocation.getter(#subtotalAmount),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get discountAmount => (super.noSuchMethod(
        Invocation.getter(#discountAmount),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double get totalAmount => (super.noSuchMethod(
        Invocation.getter(#totalAmount),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.CartItem? getCartItem(String? productId) => (super.noSuchMethod(
        Invocation.method(
          #getCartItem,
          [productId],
        ),
        returnValueForMissingStub: null,
      ) as _i3.CartItem?);

  @override
  _i5.Future<void> loadCartWithDependencies({
    required int? vendorType,
    double? lat,
    double? lon,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadCartWithDependencies,
          [],
          {
            #vendorType: vendorType,
            #lat: lat,
            #lon: lon,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> checkUpsellOpportunities(int? vendorType) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkUpsellOpportunities,
          [vendorType],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> fetchRecommendations({
    int? type,
    double? lat,
    double? lon,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchRecommendations,
          [],
          {
            #type: type,
            #lat: lat,
            #lon: lon,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  bool isItemDiscounted(String? itemId) => (super.noSuchMethod(
        Invocation.method(
          #isItemDiscounted,
          [itemId],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Future<void> selectCampaign(_i6.Campaign? campaign) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectCampaign,
          [campaign],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeCampaign() => (super.noSuchMethod(
        Invocation.method(
          #removeCampaign,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> applyCoupon(String? code) => (super.noSuchMethod(
        Invocation.method(
          #applyCoupon,
          [code],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeCoupon() => (super.noSuchMethod(
        Invocation.method(
          #removeCoupon,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadCart() => (super.noSuchMethod(
        Invocation.method(
          #loadCart,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addItem(
    _i4.Product? product,
    _i7.BuildContext? context, {
    List<Map<String, dynamic>>? selectedOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addItem,
          [
            product,
            context,
          ],
          {#selectedOptions: selectedOptions},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeItem(String? itemId) => (super.noSuchMethod(
        Invocation.method(
          #removeItem,
          [itemId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> increaseQuantity(String? itemId) => (super.noSuchMethod(
        Invocation.method(
          #increaseQuantity,
          [itemId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> decreaseQuantity(String? itemId) => (super.noSuchMethod(
        Invocation.method(
          #decreaseQuantity,
          [itemId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
