// Mocks generated by Mockito 5.4.4 from annotations
// in mobile/test/services/api_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mobile/features/products/data/models/product.dart' as _i6;
import 'package:mobile/features/vendors/data/models/vendor.dart' as _i7;
import 'package:mobile/services/api_request_scheduler.dart' as _i2;
import 'package:mobile/services/cache_service.dart' as _i5;
import 'package:mobile/services/connectivity_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRequestPermit_0 extends _i1.SmartFake implements _i2.RequestPermit {
  _FakeRequestPermit_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i3.ConnectivityService {
  @override
  _i4.Stream<bool> get connectivityStream => (super.noSuchMethod(
        Invocation.getter(#connectivityStream),
        returnValue: _i4.Stream<bool>.empty(),
        returnValueForMissingStub: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);

  @override
  bool get isOnline => (super.noSuchMethod(
        Invocation.getter(#isOnline),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Future<bool> checkConnectivity() => (super.noSuchMethod(
        Invocation.method(
          #checkConnectivity,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheService extends _i1.Mock implements _i5.CacheService {
  @override
  _i4.Future<void> cacheProducts(List<_i6.Product>? products) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheProducts,
          [products],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.Product>?> getCachedProducts() => (super.noSuchMethod(
        Invocation.method(
          #getCachedProducts,
          [],
        ),
        returnValue: _i4.Future<List<_i6.Product>?>.value(),
        returnValueForMissingStub: _i4.Future<List<_i6.Product>?>.value(),
      ) as _i4.Future<List<_i6.Product>?>);

  @override
  _i4.Future<void> cacheCategories(List<String>? categories) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheCategories,
          [categories],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<String>?> getCachedCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCachedCategories,
          [],
        ),
        returnValue: _i4.Future<List<String>?>.value(),
        returnValueForMissingStub: _i4.Future<List<String>?>.value(),
      ) as _i4.Future<List<String>?>);

  @override
  _i4.Future<void> cacheVendors(List<_i7.Vendor>? vendors) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheVendors,
          [vendors],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.Vendor>?> getCachedVendors() => (super.noSuchMethod(
        Invocation.method(
          #getCachedVendors,
          [],
        ),
        returnValue: _i4.Future<List<_i7.Vendor>?>.value(),
        returnValueForMissingStub: _i4.Future<List<_i7.Vendor>?>.value(),
      ) as _i4.Future<List<_i7.Vendor>?>);

  @override
  _i4.Future<void> cacheProfile(Map<String, dynamic>? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheProfile,
          [profile],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> getCachedProfile() => (super.noSuchMethod(
        Invocation.method(
          #getCachedProfile,
          [],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
        returnValueForMissingStub: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> clearAllCache() => (super.noSuchMethod(
        Invocation.method(
          #clearAllCache,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> getCacheInfo() => (super.noSuchMethod(
        Invocation.method(
          #getCacheInfo,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
}

/// A class which mocks [ApiRequestScheduler].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiRequestScheduler extends _i1.Mock
    implements _i2.ApiRequestScheduler {
  @override
  _i4.Future<_i2.RequestPermit> acquire({bool? highPriority = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #acquire,
          [],
          {#highPriority: highPriority},
        ),
        returnValue: _i4.Future<_i2.RequestPermit>.value(_FakeRequestPermit_0(
          this,
          Invocation.method(
            #acquire,
            [],
            {#highPriority: highPriority},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.RequestPermit>.value(_FakeRequestPermit_0(
          this,
          Invocation.method(
            #acquire,
            [],
            {#highPriority: highPriority},
          ),
        )),
      ) as _i4.Future<_i2.RequestPermit>);
}
