// File generated by FlutterFire CLI (manually reconstructed)
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdpZK0PK7y8W2f_JAoglmhy-or3XvRuyU',
    appId: '1:493893474454:android:648dc4d891eb6213a68ab7',
    messagingSenderId: '493893474454',
    projectId: 'talabi-9fc59',
    storageBucket: 'talabi-9fc59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO1YX_oOJTrvp-YsW_S5yfMqhEGPJLO0A',
    appId: '1:493893474454:ios:27b0c28c7d2add3ca68ab7',
    messagingSenderId: '493893474454',
    projectId: 'talabi-9fc59',
    storageBucket: 'talabi-9fc59.firebasestorage.app',
    iosClientId:
        '493893474454-mq1q8gionn1kai9e2q2moakt89td3r73.apps.googleusercontent.com',
    iosBundleId: 'com.talabi.mobile',
  );
}
